---
services:
  caddy:
    image: caddy:v2.10.0
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - vaultwarden
      - osticket
      - syncthing
      - bentopdf
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:v1.35.0
    volumes:
      - vw_data:/data
    environment:
      - ADMIN_TOKEN=CHANGE_ME
    restart: unless-stopped

  osticket:
    image: osticket/osticket:v1.18.2
    depends_on:
      - osticket_db
    restart: unless-stopped

  osticket_db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGE_ME
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=CHANGE_ME
    volumes:
      - osticket_db_data:/var/lib/mysql
    restart: unless-stopped

  syncthing:
    image: syncthing/syncthing:v2.0.12
    ports:
      - "8384:8384"
    restart: unless-stopped

  bentopdf:
    image: bentopdf/bentopdf:latest
    restart: unless-stopped

volumes:
  vw_data:
  osticket_db_data:
